name: Deploy Node Service to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservices-repo/node-service:${{ github.sha }} .
          docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservices-repo/node-service:${{ github.sha }}

      - name: Deploy to GKE
        run: |
          # Використовуємо твою назву кластера та локацію
          gcloud container clusters get-credentials music-cluster --region europe-central2 --project ${{ secrets.GCP_PROJECT_ID }}

          # Команда оновлення: міняємо стару версію на нову по хешу коміту
          kubectl set image deployment/node-service-deployment node-service-container=europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/microservices-repo/node-service:${{ github.sha }}

          # Чекаємо, поки Kubernetes успішно перезапустить поди
          kubectl rollout status deployment/node-service-deployment
